#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

env

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

cat ${OPENSHIFT_REPO_DIR}requirements.txt

pip install -r ${OPENSHIFT_REPO_DIR}requirements.txt
find $OPENSHIFT_REPO_DIR -name manage.py

# We don't have sentry yet
# python ${OPENSHIFT_REPO_DIR}manage.py raven test

python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput

python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput

if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
    mkdir $OPENSHIFT_DATA_DIR/media
fi

ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media
